services: 
  app: 
    build: ./ 
    image: onf/app
    container_name: onf-app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - C:\Projects\onfly:/var/www/html
    depends_on:
      - db
      - db_travel_orders
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: onfly
      MYSQL_USER: lucas
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-network

  db:
    image: mariadb:11.5
    container_name: onf-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: onfly
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  db_travel_orders:
    image: mariadb:11.5
    container_name: onf-mariadb-travel-orders
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: travel_orders
      MYSQL_USER: travel_user
      MYSQL_PASSWORD: travel_password
    volumes:
      - travel-orders-db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: onf-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-network

  phpmyadmin_travel_orders:
    image: phpmyadmin/phpmyadmin
    container_name: onf-phpmyadmin-travel-orders
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db_travel_orders
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  travel-orders-db-data:
